Repository brain-tec/product-pack, pull requests merged in 2022-11, with the labels that each got.

#10 Syncing from upstream OCA/product-pack (14.0)
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  product_pack/__manifest__.py
  product_pack/i18n/ca.po
  product_pack/i18n/es.po
  product_pack/i18n/fr.po
  product_pack/i18n/nl.po
  product_pack/i18n/product_pack.pot
  product_pack/i18n/pt.po
  product_pack/i18n/sv.po
  product_pack/models/__init__.py
  product_pack/models/product_pricelist.py
  product_pack/models/product_product.py
  product_pack/models/product_template.py
Labels: 14.0

#11 Syncing from upstream OCA/product-pack (13.0)
  README.md
  stock_product_pack/__manifest__.py
  stock_product_pack/models/product_product.py
Labels: 13.0

#13 [t132771] import stock_product_pack
  setup/stock_product_pack/odoo/addons/stock_product_pack
  setup/stock_product_pack/setup.py
  stock_product_pack/README.rst
  stock_product_pack/__init__.py
  stock_product_pack/__manifest__.py
  stock_product_pack/i18n/es.po
  stock_product_pack/i18n/fr.po
  stock_product_pack/i18n/pt.po
  stock_product_pack/i18n/stock_product_pack.pot
  stock_product_pack/models/__init__.py
  stock_product_pack/models/product_product.py
  stock_product_pack/models/product_template.py
  stock_product_pack/models/stock_rule.py
  stock_product_pack/readme/CONTRIBUTORS.rst
  stock_product_pack/readme/DESCRIPTION.rst
  stock_product_pack/readme/USAGE.rst
  stock_product_pack/security/ir.model.access.csv
  stock_product_pack/static/description/icon.png
  stock_product_pack/static/description/index.html
  stock_product_pack/tests/__init__.py
  stock_product_pack/tests/test_stock_product_pack.py
  stock_product_pack/views/product_template_views.xml
Labels: 15.0.project_gr_646.t132771

#14 [t132675] Add sale_product_pack
  sale_product_pack/README.rst
  sale_product_pack/__init__.py
  sale_product_pack/__manifest__.py
  sale_product_pack/demo/product_pack_line_demo.xml
  sale_product_pack/i18n/ca.po
  sale_product_pack/i18n/ca_ES.po
  sale_product_pack/i18n/es.po
  sale_product_pack/i18n/fr.po
  sale_product_pack/i18n/nl.po
  sale_product_pack/i18n/pt.po
  sale_product_pack/i18n/sale_product_pack.pot
  sale_product_pack/models/__init__.py
  sale_product_pack/models/product_pack_line.py
  sale_product_pack/models/sale_order.py
  sale_product_pack/models/sale_order_line.py
  sale_product_pack/readme/CONTRIBUTORS.rst
  sale_product_pack/readme/DESCRIPTION.rst
  sale_product_pack/readme/ROADMAP.rst
  sale_product_pack/readme/USAGE.rst
  sale_product_pack/security/ir.model.access.csv
  sale_product_pack/static/description/icon.png
  sale_product_pack/static/description/index.html
  sale_product_pack/tests/__init__.py
  sale_product_pack/tests/test_sale_product_pack.py
  sale_product_pack/views/product_pack_line_views.xml
  setup/sale_product_pack/odoo/addons/sale_product_pack
  setup/sale_product_pack/setup.py
Labels: 15.0.project_gr_646

#15 [t132771] Add stock_product_pack
  setup/stock_product_pack/odoo/addons/stock_product_pack
  setup/stock_product_pack/setup.py
  stock_product_pack/README.rst
  stock_product_pack/__init__.py
  stock_product_pack/__manifest__.py
  stock_product_pack/i18n/es.po
  stock_product_pack/i18n/fr.po
  stock_product_pack/i18n/pt.po
  stock_product_pack/i18n/stock_product_pack.pot
  stock_product_pack/models/__init__.py
  stock_product_pack/models/product_product.py
  stock_product_pack/models/product_template.py
  stock_product_pack/models/stock_rule.py
  stock_product_pack/readme/CONTRIBUTORS.rst
  stock_product_pack/readme/DESCRIPTION.rst
  stock_product_pack/readme/USAGE.rst
  stock_product_pack/security/ir.model.access.csv
  stock_product_pack/static/description/icon.png
  stock_product_pack/static/description/index.html
  stock_product_pack/tests/__init__.py
  stock_product_pack/tests/test_stock_product_pack.py
  stock_product_pack/views/product_template_views.xml
Labels: 15.0.project_gr_646

#16 Syncing from upstream OCA/product-pack (13.0)
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  website_sale_product_pack/__manifest__.py
  website_sale_product_pack/models/sale_order.py
Labels: 13.0

#17 Syncing from upstream OCA/product-pack (15.0)
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: 15.0
